name: Pylint Code Quality Check

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  workflow_dispatch:  # Allows manual runs from GitHub UI

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"  # Change as needed

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      - name: Run Pylint
        run: pylint regex_ease --rcfile=.pylintrc