name: Run Unit Tests and Check Coverage

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  workflow_dispatch:  # Allows manual runs from GitHub UI

jobs:
  unittests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov
          pip install -e .

      - name: Run Unit Tests with Coverage
        run: |
          pytest --cov=regex_ease --cov-report=term-missing --cov-fail-under=100